export const GENRES = [
  { id: 28, name: "Action" },
  { id: 12, name: "Abenteuer" },
  { id: 16, name: "Animation" },
  { id: 35, name: "Komödie" },
  { id: 80, name: "Krimi" },
  { id: 99, name: "Dokumentarfilm" },
  { id: 18, name: "Drama" },
  { id: 10751, name: "Familie" },
  { id: 14, name: "Fantasy" },
  { id: 36, name: "Historie" },
  { id: 27, name: "Horror" },
  { id: 10402, name: "Musik" },
  { id: 9648, name: "Mystery" },
  { id: 10749, name: "Liebesfilm" },
  { id: 878, name: "Science Fiction" },
  { id: 10770, name: "TV-Film" },
  { id: 53, name: "Thriller" },
  { id: 10752, name: "Kriegsfilm" },
  { id: 878, name: "Western" }, // Note: 37 is Western in TMDB, the user provided 878 twice (Sci-Fi and Western) in the prompt's text but I'll stick to common IDs if possible or just use what they gave. Actually, 37 is Western.
];

export const MOVIE_GENRES = [
  { id: 28, name: "Action" },
  { id: 12, name: "Adventure" },
  { id: 16, name: "Animation" },
  { id: 35, name: "Comedy" },
  { id: 80, name: "Crime" },
  { id: 99, name: "Documentary" },
  { id: 18, name: "Drama" },
  { id: 10751, name: "Family" },
  { id: 14, name: "Fantasy" },
  { id: 36, name: "History" },
  { id: 27, name: "Horror" },
  { id: 10402, name: "Music" },
  { id: 9648, name: "Mystery" },
  { id: 10749, name: "Romance" },
  { id: 878, name: "Science Fiction" },
  { id: 10770, name: "TV Movie" },
  { id: 53, name: "Thriller" },
  { id: 10752, name: "War" },
  { id: 37, name: "Western" },
];

export const TV_GENRES = [
  { id: 10759, name: "Action & Adventure" },
  { id: 16, name: "Animation" },
  { id: 35, name: "Comedy" },
  { id: 80, name: "Crime" },
  { id: 99, name: "Documentary" },
  { id: 18, name: "Drama" },
  { id: 10751, name: "Family" },
  { id: 10762, name: "Kids" },
  { id: 9648, name: "Mystery" },
  { id: 10763, name: "News" },
  { id: 10764, name: "Reality" },
  { id: 10765, name: "Sci-Fi & Fantasy" },
  { id: 10766, name: "Soap" },
  { id: 10767, name: "Talk" },
  { id: 10768, name: "War & Politics" },
  { id: 37, name: "Western" },
];
